from typing import List, Optional
from app.models.schemas import ExecutionPlan, Assumption, Milestone, JtbdStory


def export_to_markdown(plan: ExecutionPlan) -> str:
    lines = [
        f"# Execution Plan: {plan.conceptName}",
        "",
        "## Jobs-to-be-Done",
        "",
    ]
    for story in plan.jtbdFramework:
        lines.append(f"- **{story.role}**: {story.situation} → {story.outcome} *({story.dimension})*")
    lines.append("")

    if plan.momTestValidation:
        lines.extend([
            "## Mom Test Validation",
            "",
            f"**Hypothesis:** {plan.momTestValidation.targetHypothesis}",
            f"**Workflow:** {plan.momTestValidation.executionWorkflow}",
            "",
            "### Behavioral Questions",
            "",
        ])
        for q in plan.momTestValidation.behavioralQuestions:
            lines.append(f"- {q}")
        lines.append("")

    lines.extend([
        "## Risk-Assumptions Prioritization Matrix",
        "",
        "| Category | Statement | Importance | Evidence | Risk Score |",
        "|----------|-----------|------------|----------|------------|",
    ])
    for a in plan.prioritizedAssumptions:
        lines.append(f"| {a.category} | {a.statement} | {a.importance} | {a.evidence} | {a.validationScore} |")
    lines.append("")

    lines.extend([
        "## Milestones: 30/60/90-Day Execution Roadmap",
        "",
    ])
    for m in plan.milestones:
        lines.append(f"### {m.phase}: {m.objective}")
        lines.append("")
        for task in m.tasks:
            deps = ", ".join(task.dependencies) if task.dependencies else "None"
            alt = f" | *Alt:* {task.alternativeApproach}" if task.alternativeApproach else ""
            lines.append(f"- [{task.durationDays}d] {task.title} (complexity: {task.complexity}, deps: {deps}){alt}")
        lines.append("")

    if plan.governance and plan.governance.governanceWarning:
        lines.extend([
            "## Governance & Safety",
            "",
            f"**Warning:** {plan.governance.governanceWarning}",
            f"**Confidence:** {plan.governance.confidenceIndex}",
            f"**Needs Approval:** {'Yes' if plan.governance.requiresHumanApproval else 'No'}",
            "",
        ])

    return "\n".join(lines)


def export_to_shell_script(plan: ExecutionPlan, filename: str = "execute_plan.sh") -> str:
    lines = [
        "#!/bin/bash",
        f"# Auto-generated execution script for: {plan.conceptName}",
        "# Generated by ZeroOne Engine",
        "",
        "echo '========================================'",
        "echo '  ZeroOne Execution Plan'",
        f"echo '  {plan.conceptName}'",
        "echo '========================================'",
        "",
    ]
    for i, milestone in enumerate(plan.milestones, 1):
        lines.append(f"echo ''")
        lines.append(f"echo '=== Phase {i}: {milestone.objective} ==='")
        lines.append(f"echo 'Duration: {milestone.phase}'")
        lines.append("")
        for task in milestone.tasks:
            lines.append(f"echo '  - [{task.durationDays}d] {task.title}'")
        lines.append("")
        lines.append(f"echo '--- End of Phase {i} ---'")

    lines.extend([
        "",
        "echo ''",
        "echo '========================================'",
        "echo '  Plan execution complete'",
        "echo '========================================'",
    ])

    return "\n".join(lines)
